### ISSUE TITLE
wakari-server builds persistently failing on upload

### ISSUE THREAD

**Issue by mmarchetti** [Anaconda-Server/anaconda-build#108]
for example: https://anaconda.org/wakari/wakari-server/builds/685/0

Build and test succeed, but upload fails with: 
`[TypeError] cannot make memory view because object does not have the buffer interface` 

down in the Requests library.

**Comment by srossross** [comment]
```
binstar -q -t $TOKEN upload --force --user wakari --package wakari-server  --channel dev /home/binstar/miniconda/conda-bld/linux-64/*.tar.bz2 --build-id 685.0
Using binstar api site https://api.anaconda.org
[TypeError] cannot make memory view because object does not have the buffer interface 
Traceback (most recent call last):
  File "/home/binstar/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 422, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/binstar/miniconda/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/home/binstar/miniconda/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/home/binstar/miniconda/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/home/binstar/miniconda/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/home/binstar/miniconda/lib/python2.7/httplib.py", line 866, in send
    self.sock.sendall(datablock)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
    data = memoryview(data)
TypeError: cannot make memory view because object does not have the buffer interface
 

```

**Comment by mmarchetti** [comment]
It's not just the wakari-server failing with this error now - it appears to be all of the packages we attempt to build.

**Comment by srossross** [comment]
@mmarchetti I think this could be because I set up this build worker to use python3 Perhaps there is an issue with the python3 upload command... testing this now.

cc @rafaelhbarros

**Comment by dsludwig** [comment]
This is the same issue as anaconda-server/anaconda-client#222

**Comment by srossross** [comment]
Closing this issue because it is a duplicate.
