### ISSUE TITLE
anaconda-build does not install .bat, .sh default files

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#120]
In a new install, I am getting the error that the <code>data</code> dir is not being copied to the target installation dir.  This data dir should contain the default windows and bash build scripts:
When running a worker or su_worker, I encountered as root:

```bash
[TemplateNotFound] build_script.sh 
Traceback (most recent call last):
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_86.g7022e44.dirty-py2.7.egg/binstar_build_client/worker/worker.py", line 147, in _handle_job
    failed, status = self.build(job_data)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_86.g7022e44.dirty-py2.7.egg/binstar_build_client/worker/worker.py", line 251, in build
    job_data, conda_build_dir=self.args.conda_build_dir)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_86.g7022e44.dirty-py2.7.egg/binstar_build_client/worker/utils/script_generator.py", line 175, in gen_build_script
    build_script_template = env.get_or_select_template('build_script.sh')
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: build_script.sh
```
In a root install and root user:
ls /opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_86.g7022e44.dirty-py2.7.egg/binstar_build_client/worker/utils/

#### ./data is not there

Is this a MANIFEST.in or setup.py correction needed?

**Comment by srossross** [comment]
@PeterDSteinberg did you fix this issue? I think that this is working for me in the latest conda anaconda-build package.
