### ISSUE TITLE
UnicodeDecodeError in writing build log to server

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#121]
Just observed this using anaconda worker run ... and doing anaconda build submit ./anaconda-server --queue psteinberg/abc
```
[UnicodeEncodeError] ascii 
Traceback (most recent call last):
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_89.g5cdf76c.dirty-py2.7.egg/binstar_build_client/worker/worker.py", line 147, in _handle_job
    failed, status = self.build(job_data)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_89.g5cdf76c.dirty-py2.7.egg/binstar_build_client/worker/worker.py", line 292, in build
    return failed, status
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_89.g5cdf76c.dirty-py2.7.egg/binstar_build_client/worker/utils/build_log.py", line 65, in write
    terminate_build = self.write_to_server(msg)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/binstar_build-0.12.1_89.g5cdf76c.dirty-py2.7.egg/binstar_build_client/mixins/build_queue.py", line 41, in log_build_output
    res = self.session.post(url, data=msg)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/opt/anaconda/envs/anaconda.org/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
```

**Comment by srossross** [comment]
@PeterDSteinberg what commit are you on? can you pull and try again?

**Comment by PeterDSteinberg** [comment]
I should have mentioned above that I am seeing this in the feature/su_build_users branch after merging develop's gevent related code into there.  I just tested on the latest develop and this UnicodeDecodeError did not happen.

**Comment by stephenakearns** [comment]
Hi @PeterDSteinberg  - @srossross is thinking this is fixed - can you review and close if appropriate.

**Comment by srossross** [comment]
Closing this -- @PeterDSteinberg reopen if this is still an issue.
