### ISSUE TITLE
traceback unnecessarily printed for nonexistent packages (list-all)

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#153]
When running ```anaconda build list-all psteinberg/does-not-exist-package``` I usually get:

```
$ anaconda build list-all psteinberg/does-not-exist
Using anaconda-server api site http://api.anaconda.org
Getting builds:
        Build # |          Status |        Platform |          Engine |             Env
--------------- + --------------- + --------------- + --------------- + ---------------
[NotFound] (u"The path u'/build/psteinberg/does-not-exist' could not be found", 404)
```

which makes sense.  However sometimes I get the full traceback for that NotFound error, like this:
```

Using anaconda-server api site http://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/Users/psteinberg/anaconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/Users/psteinberg/anaconda/lib/python2.7/site-packages/anaconda_client-1.1.2+6.g2136f7d.dirty-py2.7.egg/binstar_client/scripts/cli.py", line 80, in main
    description=__doc__, version=version)
  File "/Users/psteinberg/anaconda/lib/python2.7/site-packages/anaconda_client-1.1.2+6.g2136f7d.dirty-py2.7.egg/binstar_client/scripts/cli.py", line 62, in binstar_main
    return args.main(args)
  File "/Users/psteinberg/anaconda/lib/python2.7/site-packages/binstar_build_client/build_commands/info.py", line 76, in list_builds
    for build in binstar.builds(args.package.user, args.package.name, args.build_no):
  File "/Users/psteinberg/anaconda/lib/python2.7/site-packages/binstar_build_client/mixins/build.py", line 92, in builds
    self._check_response(res)
  File "/Users/psteinberg/anaconda/lib/python2.7/site-packages/anaconda_client-1.1.2+6.g2136f7d.dirty-py2.7.egg/binstar_client/__init__.py", line 161, in _check_response
    raise ErrCls(msg, res.status_code)
NotFound: (u"The path u'/build/conda-team/protoci-cytoolz' could not be found", 404)
Getting builds:
        Build # |          Status |        Platform |          Engine |             Env
--------------- + --------------- + --------------- + --------------- + ---------------
```

**Comment by PeterDSteinberg** [comment]
The uncaught exception only occurs when running ```anaconda build list-all username/nonexistent-package``` from a Python subprocess.

**Comment by PeterDSteinberg** [comment]
I have decided this is a non issue.  When running ```anaconda build list-all psteinberg/nonexistent``` in a subprocess I apparently had a different setting for ```--show-traceback```.  I'm now able to run in subprocess without the error.  Closing this issue.
