### ISSUE TITLE
Temp Data is placed into incorrect folder during conda build with configured root-dir

### ISSUE THREAD

**Issue by cruser42** [Anaconda-Server/anaconda-build#185]
I have this setting in my condarc
```
conda-build:
    root-dir: C:\Code\builds
```
However, one of the folders is not created there. Instead, the directory 'Code\builds' is created within my Anaconda folder

Folder is incorrectly created and files deposited here:
`C:\apps\Anaconda\2.3\Code\builds\work`

it probably SHOULD be here:
`C:\Code\builds\work`

When I killed a build halfway through, and re-ran without cleaning up, the following traceback is produced. Notice the last line indicating where conda-build is trying to store the files.

```
C:\Code\project\myproject>conda build conda_recipie
Removing old build environment
Removing old work directory
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\apps\anaconda\2.3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\apps\anaconda\2.3\lib\site-packages\conda_build\main_build.py", line 190, in main
    args_func(args, p)
  File "C:\apps\anaconda\2.3\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\apps\anaconda\2.3\lib\site-packages\conda_build\main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "C:\apps\anaconda\2.3\lib\site-packages\conda_build\build.py", line 370, in build
    move_to_trash(source.WORK_DIR, '')
  File "C:\apps\anaconda\2.3\lib\site-packages\conda\install.py", line 548, in move_to_trash
    return move_path_to_trash(join(prefix, f))
  File "C:\apps\anaconda\2.3\lib\site-packages\conda\install.py", line 579, in move_path_to_trash
    shutil.move(path, trash_dir)
  File "C:\apps\anaconda\2.3\lib\shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path 'C:\apps\anaconda\2.3\pkgs\.trash\tmp0vtigx\..\..\..\Code\builds\work\work' already exists
```

**Comment by srossross** [comment]
@cruser42 I am going moving this to the conda-build repo.

**Comment by srossross** [comment]
See conda/conda#746

**Comment by treetoc** [comment]
Same symptom here but slightly different setup:
- A [buildbot](http://buildbot.net/) server is launching a batch job that create a conda environment
- We create the env using:
` conda create -p %CONDA_ENV_DIR% --file %CD%\..\conda_requirements.txt --yes -q -m -c http://conda.mycompany.local/prod/`
- Scripts execute fine
- We (try to) clean the environment using:
`conda remove -p %CONDA_ENV_DIR% --all --yes -c http://conda.mycompany.local/prod/`

The result is a similar log where the file to be removed are move to c:\Anaconda\pkgs\.trash\myproject\ instead of c:\Anaconda\pkgs\.trash\unique_tmp_directory\myproject\

`
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at
        
        https://github.com/conda/conda/issues
    
    Include the output of the command 'conda info' in your report.
    
    
    Using Anaconda Cloud api site https://api.anaconda.org
    Traceback (most recent call last):
      File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
        sys.exit(main())
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 139, in main
        args_func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 146, in args_func
        args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_remove.py", line 203, in execute
       plan.execute_actions(actions, index, verbose=not args.quiet)
      File "C:\Anaconda\lib\site-packages\conda\plan.py", line 539, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 96, in UNLINK_CMD
        install.unlink(state['prefix'], arg)
      File "C:\Anaconda\lib\site-packages\conda\install.py", line 723, in unlink
        move_path_to_trash(dst)
      File "C:\Anaconda\lib\site-packages\conda\install.py", line 594, in move_path_to_trash
        shutil.move(path, trash_dir)
      File "C:\Anaconda\lib\shutil.py", line 292, in move
        raise Error, "Destination path '%s' already exists" % real_dst
     shutil.Error: Destination path 'C:\Anaconda\pkgs\.trash\tmpuknbbm\..\opt\buildbot-slave\slave\myproject_windows_build\myproject\_tmp_conda_env\DLLs\_ctypes.pyd' already exists

`

In our using the explicit --copy flag to create the environment did solve the issue...
