### ISSUE TITLE
Windows CONDA_NPY setting bug

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#196]
`CONDA_NPY` can end up being set to literally `""` rather than an empty string when numpy is not present, at least on Windows.  Make sure that CONDA_NPY is undefined if numpy is not installed.

**Comment by PeterDSteinberg** [comment]
Here's the bottom part of my build log with the error that results, see the quoting of `CONDA_NPY ""` on the second line:
```
CONDA_PY 27
CONDA_NPY ""

[Fetching Build Source]
The system cannot find the file specified.
git clone --recursive --depth=50 --branch=master https://github.com/PeterDSteinberg/myorg.package1.git "C:\Users\binstar\builds\psteinberg\myorg.package1\source"
Cloning into 'C:\Users\binstar\builds\psteinberg\myorg.package1\source'...
"git checkout --quiet e19d0bccff2199a388a1cf143600337a722f732d"

[Script]
conda build .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\binstar\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py", line 110, in main
    args_func(args, p)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py", line 312, in args_func
    args.func(args, p)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py", line 181, in execute
    import conda_build.build as build
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\build.py", line 29, in <module>
    from conda_build import environ, source, tarcheck
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\environ.py", line 11, in <module>
    from conda_build.config import config
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\config.py", line 16, in <module>
    class Config(object):
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\config.py", line 24, in Config
    CONDA_NPY = int(os.getenv('CONDA_NPY', '19').replace('.', ''))
ValueError: invalid literal for int() with base 10: '"" '
```
