### ISSUE TITLE
Issues setting up Anaconda build to pull from something other than default

### ISSUE THREAD

**Issue by mariusvniekerk** [Anaconda-Server/anaconda-build#225]
Full log here
https://anaconda.org/mvn/cyavro/builds/12/0/log

It seems anaconda-build never creates the condarc file needed?

```
export CONDARC=/home/anaconda/worker-2/builds/mvn/cyavro/condarc
touch: cannot touch `/home/anaconda/worker-2/builds/mvn/cyavro/condarc': No such file or directory
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main_config.py", line 207, in execute
    execute_config(args, parser)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main_config.py", line 440, in execute_config
    with open(rc_path, 'w') as rc:
IOError: [Errno 2] No such file or directory: '/home/anaconda/worker-2/builds/mvn/cyavro/condarc'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.
```

Am i missing something obvious somewhere?

**Comment by dsludwig** [comment]
@mariusvniekerk you are not doing anything wrong - it looks like the docker worker mixes up the working directory on the host machine and the docker container since this commit: https://github.com/Anaconda-Server/anaconda-build/commit/f276e776c2dda15b7c0d842675600d79a9b49967

cc @PeterDSteinberg

**Comment by dsludwig** [comment]
@mariusvniekerk we have updated the workers with the latest version of anaconda-build `0.15.0` which should fix this issue. Please let me know if you have any other problems.

Thanks for reporting the issue!

**Comment by mariusvniekerk** [comment]
Tested and it works
