### ISSUE TITLE
Build Worker - pyOpenSSL unicode error on python2

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/anaconda-build#41]
```
[Build Targets]
binstar -q -t %TOKEN% upload --force --user binstar --package chalmers  --channe
l dev C:\Users\binstar\Miniconda\conda-bld\win-64\*.tar.bz2 --build-id 167
Using binstar api site https://api.binstar.org
[TypeError] data must be a byte string
Traceback (most recent call last):
  File "C:\Users\binstar\Miniconda\Scripts\binstar-script.py", line 9, in <modul
e>
    load_entry_point('binstar==0.10.1', 'console_scripts', 'binstar')()
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\scripts\cli.
py", line 94, in main
    description=__doc__, version=version)
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\scripts\cli.
py", line 76, in binstar_main
    return args.main(args)
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\commands\upl
oad.py", line 202, in main
    callback=upload_print_callback(args))
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\__init__.py"
, line 423, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, t
imeout=10 * 60 * 60, headers=headers)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\api.py", line 108,
 in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\api.py", line 50,
in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\sessions.py", line
 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\sessions.py", line
 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\adapters.py", line
 370, in send
    timeout=timeout
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
onnectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
onnectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 848, in _send_output
    self.send(message_body)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 817, in send
    self.sock.sendall(datablock)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 225, in sendall
    sent = self._send_until_done(data)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 215, in _send_until_done
    return self.connection.send(data)
  File "C:\Users\binstar\Miniconda\lib\site-packages\OpenSSL\SSL.py", line 947,
in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string
```

**Comment by srossross** [comment]
@malev @asmeurer has seen this error before and says that it is an issue with the way that requests is interacting with pyopenssl.

**Comment by malev** [comment]
We roll back to revision 19 (win 32 machine). That removed pyopenssl and that is how we fixed this **for now**

**Comment by srossross** [comment]
@malev what is the `conda list` of the versions?

**Comment by malev** [comment]
```
PS C:\Users\binstar> conda list
# packages in environment at C:\Users\binstar\Miniconda:
#
Could not extract name and version from: 'You are using pip version 6.0.8, however version 6.1.1 is available.'
Could not extract name and version from: "You should consider upgrading via the 'pip install --upgrade pip' command."
binstar                   0.8.1                    py27_8
binstar-build             0.10.5                    <pip>
chalmers                  0.3.0                   py27_12
clyent                    0.3.4                    py27_0
conda                     3.10.1                   py27_0
conda-build               1.11.0                   py27_0
conda-env                 2.1.4                    py27_0
dateutil                  2.1                      py27_2
jinja2                    2.7.3                    py27_2
markupsafe                0.23                     py27_0
menuinst                  1.0.4                    py27_0
pip                       6.0.8                    py27_0
psutil                    2.1.1                    py27_0
pycosat                   0.6.1                    py27_0
python                    2.7.8                         0
python-dateutil           2.4.2                     <pip>
pytz                      2014.7                   py27_0
pywin32                   219                      py27_0
pyyaml                    3.11                     py27_0
requests                  2.6.0                    py27_0
setuptools                15.0                     py27_0
six                       1.8.0                    py27_0
unxutils                  2013.04.24                    0
PS C:\Users\binstar>
```

**Comment by stephenakearns** [comment]
@dsludwig - Reading the comments on this bug, I'm wondering if this issue will also be closed when we get the updated requests lib. Moving it to the externally blocked pipeline. Let me know if that's not the case

**Comment by dsludwig** [comment]
This should be fixed with the latest releases of anaconda-client and requests.
