### ISSUE TITLE
Linux 64, Linux 32 and Windows boxes/queues are down

### ISSUE THREAD

**Issue by danielfrg** [Anaconda-Server/anaconda-build#58]
I dont know if this is the right place, let me know if its not and i will move it.

Something is down in anaconda.org the boxes, the queues, i dont know. They have been down for a while. I am getting this error in all my builds:

```
Build 233.1 Sumitted id:55942e063273af558716dd01
There are no available build workers in the queue build-binstar-continuum for the platform linux-64 (available win-32, osx-64, win-64)
Your build was not submitted
```

**Comment by mutirri** [comment]
Both `binstar-build` workers under windows machines were killed by this error:
```
Using binstar api site https://api.anaconda.org
C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_
.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This
 prevents urllib3 from configuring SSL appropriately and may cause certain SSL c
onnections to fail. For more information, see https://urllib3.readthedocs.org/en
/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[BinstarError] Method Not Allowed: Specified method is invalid for this resource
. ([DELETE] https://api.anaconda.org/build-worker/binstar/continuum/5592a0fe22f2
e9357d8bb14a -> 405)
Traceback (most recent call last):
  File "C:\Users\binstar\Miniconda\Scripts\binstar-build-script.py", line 9, in
<module>
    load_entry_point('binstar-build==0.8.3', 'console_scripts', 'binstar-build')
()
  File "c:\users\binstar\worker\builds\binstar\binstar-build\source\binstar_buil
d_client\scripts\build.py", line 31, in main
    version=version)
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\scripts\cli.
py", line 76, in binstar_main
    return args.main(args)
  File "c:\users\binstar\worker\builds\binstar\binstar-build\source\binstar_buil
d_client\commands\worker.py", line 47, in main
    worker.work_forever()
  File "c:\users\binstar\worker\builds\binstar\binstar-build\source\binstar_buil
d_client\worker\worker.py", line 77, in work_forever
    with self.worker_context() as worker_id:
  File "C:\Users\binstar\Miniconda\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\users\binstar\worker\builds\binstar\binstar-build\source\binstar_buil
d_client\worker\worker.py", line 332, in worker_context
    self.bs.remove_worker(self.args.username, self.args.queue, worker_data['work
er_id'])
  File "c:\users\binstar\worker\builds\binstar\binstar-build\source\binstar_buil
d_client\mixins\build_queue.py", line 25, in remove_worker
    self._check_response(res, [200, 404])
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\__init__.py"
, line 160, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'Method Not Allowed: Specified method is invalid for this resour
ce. ([DELETE] https://api.anaconda.org/build-worker/binstar/continuum/5592a0fe22
f2e9357d8bb14a -> 405)', 405)
```

Maybe the most weird thing here is that scripts wants to load entry point `0.8.3` and `binstar-build` is in version `0.10.7`.
