### ISSUE TITLE
Qt dependency missing(?) on linux worker

### ISSUE THREAD

**Issue by richardotis** [Anaconda-Server/anaconda-build#79]
```
Build 9.0 Sumitted id:55dc94ac42b65d55c5c3269c
This build is in the build queue "build/binstar/public"...
Building on worker docker-1 (platform linux-64)
Starting build richardotis/pycalphad#9.0
Docker Image: continuumio/binstar-build-linux64

[snip]

===== testing package: pycalphad-0.2+14.g2bb370c-py27_0 =====
import: u'pycalphad'
Traceback (most recent call last):
  File "/opt/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import pycalphad
  File "build/bdist.linux-x86_64/egg/pycalphad/__init__.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pycalphad/plot/isotherm.py", line 8, in <module>
  File "/opt/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/opt/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 17, in <module>
    from .backend_qt5agg import NavigationToolbar2QTAgg
  File "/opt/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/opt/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/opt/miniconda/envs/_test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libXext.so.6: cannot open shared object file: No such file or directory
TESTS FAILED: pycalphad-0.2+14.g2bb370c-py27_0
command exited with status 1
discarding /home/binstar/env/bin from PATH
Exit BINSTAR_BUILD_RESULT=failure
```

**Comment by richardotis** [comment]
Today I re-launched a failed build with this error and it finished with no problems, so I'm guessing this is fixed now.
